"""Pure wrappers around a python-for-android generated service class."""

from __future__ import annotations

from typing import Protocol


class AndroidServiceClass(Protocol):
    def start(self, context: object, argument: str) -> object:
        """Start the packaged service generated by python-for-android."""

    def stop(self, context: object) -> object:
        """Stop the packaged service generated by python-for-android."""


def start_android_service(
    service_class: AndroidServiceClass,
    *,
    context: object,
    argument: str,
) -> bool:
    """Start the service and return the tracked running state."""

    service_class.start(context, argument)
    return True


def stop_android_service(
    service_class: AndroidServiceClass,
    *,
    context: object,
    started: bool,
) -> bool:
    """Stop a service that this app started and return the new running state."""

    if not started:
        return False
    service_class.stop(context)
    return False
